spring:
  profiles:
    active: prod
  application:
    name: recommendation-engine

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: recommendationEngine
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        security.protocol: SASL_SSL
        sasl.mechanism: "SCRAM-SHA-256"
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USER:user}" password="${KAFKA_PASSWORD:pswd}";
        group-id: recommendation-engine
        auto:
          offset:
            reset: earliest

properties:
  recommendation-engine:
    recommendation-factory:
      selling-out-products:
        enabled: true
      similar-products:
        enabled: true
      popular-products:
        enabled: true
      recently-viewed-products:
        enabled: true
      high-rated-products:
        enabled: true
      discounted-products:
        enabled: true
      also-bought-products:
        enabled: true
    daysLimit: 10
    maxProducts: 10
    minDiscount: 10.0
    minRating: 4.0
    pageSize: 10
    minQuantitySold: 100
    maxStocks: 10
