package com.example.recommendationengine.model;

public enum Activity {
    LOGIN, LOGOUT, VIEW_PRODUCT, ADD_TO_CART, REMOVE_FROM_CART, PURCHASE, RATE_PRODUCT, REVIEW_PRODUCT, SEARCH_PRODUCT, CLICK_PRODUCT, ADD_TO_WISHLIST, REMOVE_FROM_WISHLIST, FOLLOW_PRODUCT, SHARE_PRODUCT;
}
